project:
  type: website
  output-dir: .

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getting-started.qmd
      - sidebar:concepts
      - why.qmd
  sidebar:
  - id: ""
  - id: concepts
    title: "Concepts"
    style: "docked"
    collapse-level: 2
    contents:
      - why.qmd
      - auto: concepts/*.qmd
  - id: contribute
    title: "Contribute"
    style: "docked"
    collapse-level: 2
    contents:
      - auto: contribute

format:
  html:
    theme: solar
    toc: true



